core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls'))
]

portfolio/urls.py
from django.urls import path

from portfolio.views import HomeView

app_name = "portfolio"

urlpatterns = [
    path('', HomeView.as_view(), name="home"),
]

portfolio/views.py
from django.shortcuts import render

# Create your views here.
from django.views import View


class HomeView(View):
    template_name = 'portfolio/index.html'

    def get(self, *args, **kwargs):
        return render(self.request, self.template_name)

templates/portfolio/components/about.html
    {% load static %}
    <section class="about-area" id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <h1>about me</h1>
                </div>
                <div class="col-lg-6">
                    <div class="about-content">
                        <h3>Am a front-end developer/UI UX designer</h3>
                        <p>Am a skilled  and creative front-end developer/UI UX designer who is passionate about design.Am a team player with excellent communication skills</p>
                        <img src="{% static 'assets/image/about/signature.png' %}" alt="singnatur">
                    </div>
                    <div class="skill-wrapper">
                        <div class="skill">
                            <p>Html/Css</p>
                            <div class="skill-bar skill1 wow slideInLeft animated">
                                <span class="skill-count1">95%</span>
                            </div>
                        </div>
                        <div class="skill">
                            <p>Javascript/React</p>
                            <div class="skill-bar skill2 wow slideInLeft animated">
                                <span class="skill-count2">85%</span>
                            </div>
                        </div>
                        <div class="skill">
                            <p>Jquery/
                                AfterEffects</p>
                            <div class="skill-bar skill3 wow slideInLeft animated">
                                <span class="skill-count3">75%</span>
                            </div>
                        </div>
                        <div class="skill">
                            <p>Figma/Adobe xd</p>
                            <div class="skill-bar skill4 wow slideInLeft animated">
                                <span class="skill-count4">65%</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- ========= 1.3 About Us Area End ============== -->

templates/portfolio/components/header.html
    {% load static %}
    <!-- =============== 1.1 Menu Area Start====================-->
    <header class="header-menu" id="header">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-3">
                    <div class="logo">
                        <a href="{% url 'portfolio:home' %}"><img src="{% static 'assets/image/logo/logo.png' %}" alt="logo"></a>
                    </div>
                </div>
                <div class="col-lg-9 d-none d-lg-block">
                    <div class="main-menu">
                        <nav class="nav-menu">
                            <ul id="navigation">
                                <li class="active"><a href="#home">Home</a></li>
                                <li><a href="#about">About</a></li>
                                <li><a href="#work">work</a></li>
                                <li><a href="#portfolio">portfolo</a></li>
                                <!-- <li><a href="#blog">blog</a></li> -->
                                <li><a href="#contact">contact</a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
                <div class="col-12 d-block d-lg-none">
                    <div class="mobile_menu"></div>
                </div>
            </div>
        </div>
    </header>
    <!-- =============== 1.1 Menu Area End ====================-->

templates/portfolio/components/home.html
  {% load static %}
  <section class="home" id="home">
        <div class="profile">
            <img src="{% static 'assets/image/home/profile.jpeg' %}" alt="portfolio">
            <a class="lightbox-video" href="#">
                <div class="video">
                    <div class="play-btn">
                        <i class="fas fa-play"></i>
                    </div>
                </div>
            </a>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-6 res">
                    <div class="portfolio-content">
                        <h1>
                            <span>Hello, </span> I’m Maureen Chepkemoi
                        </h1>
                        <h4>Frontend Developer</h4>
                        <a class="theme-btn hover-target" href="{% static 'assets/cv/maureen-chepkemoi-resume.pdf' %}" download="">Download<span> CV</span></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="social-media">
            <ul>
                <li class="active"><a class="hover-target" href="https://web.facebook.com/maureen.chepkemoi.376" target="_blank"><span>facebook</span> <i class="fab fa-facebook-f"></i></a></li>
                <li><a class="hover-target" href="https://www.linkedin.com/in/maureen-chepkemoi-97b9b4171/" target="_blank"><span>linkedin</span> <i class="fab fa-linkedin-in"></i></a></li>
                <li><a class="hover-target" href="https://github.com/chepkemoi-maureen/maureen-portfolio"target="_blank"><span>github</span> <i class="fab fa-github"></i></a></li>
            </ul>
        </div>
    </section>
    <!-- =============== 1.2 Home Area End ====================-->

templates/portfolio/components/portfolio.html
    {% load static %}
    <section class="portfolio-area" id="portfolio">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 offset-lg-3">
                    <div class="section-heading">
                        <h2>My Projects</h2>
                        <p>These are the projects I have done </p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="filtering-btn">
                        <ul class="filter-button-group">
                            <li class="filter-btn active-btn" data-filter="*">All Project</li>
                            <li class="filter-btn" data-filter=".webdesign">Web Design</li>
                            <li class="filter-btn" data-filter=".uidesign">UI/UX Design</li>
                            <li class="filter-btn" data-filter=".photography">Photography</li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="row grid">
                <div class="col-lg-4 col-md-6 grid-item uidesign photography">
                    <a href="{% static 'assets/image/portfolio/1.jpg' %}" class="light-box">
                        <div class="port-img">
                            <img src="{% static 'assets/image/portfolio/image1.jpg' %}" alt="portlio-image" class="img-fluid">
                             <span>Photography</span>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-md-6 grid-item photography webdesign">
                    <a href="{% static 'assets/image/portfolio/2.jpg' %}" class="light-box">
                        <div class="port-img">
                            <img src="{% static 'assets/image/portfolio/image2.jpg' %}" alt="portlio-image" class="img-fluid">
                            <span>UI/UX Design</span>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-md-6 grid-item uidesign webdesign">
                    <a href="{% static 'assets/image/portfolio/3.jpg' %}" class="light-box">
                        <div class="port-img">
                            <img src="{% static 'assets/image/portfolio/image3.jpg' %}" alt="portlio-image" class="img-fluid">
                            <span>Web Design</span>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-md-6 grid-item webdesign photography uidesign">
                    <a href="{% static 'assets/image/portfolio/4.jpg' %}" class="light-box">
                        <div class="port-img">
                            <img src="{% static 'assets/image/portfolio/image4.jpg' %}" alt="portlio-image" class="img-fluid">
                            <span>UI/UX Design</span>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-md-6 grid-item photography uidesign">
                    <a href="{% static 'assets/image/portfolio/5.jpg' %}" class="light-box">
                        <div class="port-img">
                            <img src="{% static 'assets/image/portfolio/image5.jpg' %}" alt="portlio-image" class="img-fluid">
                            <span>Photography</span>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </section>
    <!-- =============== 1.5 Portfolio Area End ====================-->

templates/portfolio/components/work-experience.html
    {% load static %}
    <section class="work-area" id="work">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 offset-lg-3">
                    <div class="section-heading">
                        <h2>Work Experience</h2>
                        <p></p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-7 ">
                    <div class="single-work-item work-item-left">
                        <div class="work-experience text-right mr-20">
                            <h6>1 Jan, 2022 - 31 May, 2022</h6>
                            <h4>Side Hustle Company ,Nigeria.</h4>
                            <p>Implementing web design and development principles to build stable software. 
                                Bringing mock-ups to live using HTML, CSS, JavaScript.
                                Collaborating closely with the team to support projects during all phases of delivery.</p>
                        </div>
                        <div class="work-item mr-30">
                            <h6>UI/UX</h6>
                            <h6>Designer</h6>
                        </div>
                    </div>
                </div>
               
                </div>
                
    </section>
    <!-- =============== 1.4 Work Experiences Area End ====================-->

templates/portfolio/include/scripts.html
    {% load static %}
    <!-- =============== 1.9 Footer Area Start ====================-->
    <script src="{% static 'assets/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.easing.1.3.js' %}"></script>
    <script src="{% static 'assets/js/fontawesome.min.js' %}"></script>
    <script src="{% static 'assets/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'assets/js/slicknav.min.js' %}"></script>
    <script src="{% static 'assets/js/imagesloaded.pkgd.min.js' %}"></script>
    <script src="{% static 'assets/js/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'assets/js/wow.min.js' %}"></script>
    <script src="{% static 'assets/js/main.js' %}"></script>

templates/portfolio/include/styles.html
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/animate.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/owl.carousel.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/fontawesome.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/slicknav.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/magnific-popup.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/custom.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/style.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/responsive.css' %}" />

templates/portfolio/index.html
{% extends 'portfolio/layouts/base.html' %}
{% load static %}
{% block content %}
    <!-- =============== 1.2 Home Area Start ====================-->
    {% include 'portfolio/components/home.html' %}
    <!--========= 1.3 About Us Area Start ==============-->
    {% include 'portfolio/components/about.html' %}
    <!-- =============== 1.4 Work Experiences Area Start ====================-->
    {% include 'portfolio/components/work-experience.html' %}
    <!-- =============== 1.5 Portfolio Area ====================-->
    {% include 'portfolio/components/portfolio.html' %}
    <!-- =============== 1.6 Happy Clients Area ====================-->
    <div class="client-area">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 offset-lg-1">
                    <div class="client owl-carousel">
                        <div class="single-client text-center">
                            <div class="client-content">
                                <p>I have a strong understanding in Design Principles,Photoshop,Adobe indesign,After Effects</p>
                                <h5>Maureen Chepkemoi</h5>
                                <h6>Designer</h6>
                            </div>
                            <img src="{% static 'assets/image/client/client.jpg' %}" alt="client">
                        </div>
                      <!-- <div class="single-client text-center">
                          <div class="client-content">
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt labore etdolore. Quis ipsum supendsse ultrices gravida. Risus commodo iverra maecnas accumsan adipiscing elit lacus vel facilisis. </p>
                                <h5>Alvin Kont</h5>
                                <h6>Designer</h6>
                            </div>
                            <img src="{% static 'assets/image/client/client.jpg' %}" alt="client">
                        </div>-->
                      <!-- <div class="single-client text-center">
                            <div class="client-content">
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt labore etdolore. Quis ipsum supendsse ultrices gravida. Risus commodo iverra maecnas accumsan adipiscing elit lacus vel facilisis. </p>
                                <h5>Alvin Kont</h5>
                                <h6>Designer</h6>
                            </div>
                            <img src="{% static 'assets/image/client/client.jpg' %}" alt="client">
                        </div>-->
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- =============== 1.6 Happy Clients Area End ====================-->
    <!-- =============== 1.7 Blog Area  Start==================== -->
    <!-- <section class="blog-area" id="blog">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 offset-lg-3">
                    <div class="section-heading">
                        <h2>Popular Blog</h2>
                        <p>Sed ut pespciatis unde omnis iste natus error sit olptatem accusantium doloremque ludantium veritatis.</p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="blog owl-carousel">
                        <div class="single-blog">
                            <a href="blog-details.html">Creativity is nothing but the a mind set free.</a>
                            <div class="zoom">
                                <img src="{% static 'assets/image/blog/blog-1.jpg' %}" alt="blog-1">
                            </div>
                            <p>Lorem ipsum dolor sit amet, nectetur adipiscing elit, abore et dolore magna aliqua.smaecenas accumsan lacus vel facilisis. </p>
                            <div class="comment-like">
                                <ul>
                                    <li> 30 Comments</li>
                                    <li> 201 Likes</li>
                                    <li>201 Likes </li>
                                </ul>
                                <a class="theme-btn read-more" href="blog-details.html">Read Details</a>
                            </div>
                        </div>
                        <div class="single-blog">
                            <a href="blog-details.html">Adipisicing elit, sed do eiusmod tempor incididunt.</a>
                            <div class="zoom">
                                <img src="{% static 'assets/image/blog/blog-2.jpg' %}" alt="blog-2">
                            </div>
                            <p>Lorem ipsum dolor sit amet, nectetur adipiscing elit, abore et dolore magna aliqua.smaecenas accumsan lacus vel facilisis. </p>
                            <div class="comment-like">
                                <ul>
                                    <li> 30 Comments</li>
                                    <li> 201 Likes</li>
                                    <li>201 Likes </li>
                                </ul>
                                <a class="theme-btn read-more" href="blog-details.html">Read Details</a>
                            </div>
                        </div>
                        <div class="single-blog">
                            <a href="#">Laboris nisi ut aliquip ex ea commodo consequat.</a>
                            <div class="zoom">
                                <img src="{% static 'assets/image/blog/blog-3.jpg' %}" alt="blog-3">
                            </div>
                            <p>Lorem ipsum dolor sit amet, nectetur adipiscing elit, abore et dolore magna aliqua.smaecenas accumsan lacus vel facilisis. </p>
                            <div class="comment-like">
                                <ul>
                                    <li> 30 Comments</li>
                                    <li> 201 Likes</li>
                                    <li>201 Likes </li>
                                </ul>
                                <a class="theme-btn read-more" href="blog-details.html">Read Details</a>
                            </div>
                        </div>
                    </div>
                    <a class="theme-btn more-blog text-center" href="blog.html">more blog</a>
                </div>
            </div>
        </div>
    </section> -->
    <!-- =============== 1.7 Blog Area  End ====================-->
    <!-- =============== 1.8 Hire Area Start ====================-->
    <section class="hire-area" id="hire">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="hire">
                        <div class="hire-content">
                            <h3>I'm Available</h3>
                            <h2>For Freelanching</h2>
                        </div>
                        <a class="theme-btn hire-btn" href="#"> hire me</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- =============== 1.8 Hire Area Start ====================-->
    <!-- =============== 1.9 Contact Area Start ====================-->
    <section c
    lass="contact-area" id="contact">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 offset-lg-3">
                    <div class="contact-content text-center">
                        <a href="index-2.html"><img src="{% static 'assets/image/logo/logo.png' %}" alt="logo"></a>
                        <!--<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum </p>-->
                        <div class="hr"></div>
                        <h6>64 Kedowa Kericho, KE 60-200 Kenya</h6>
                        <h6>+254 768 150 184<span>|</span>+254 768 150 184</h6>
                        <div class="contact-social">
                            <ul>
                                <li><a class="hover-target" href="https://web.facebook.com/maureen.chepkemoi.376"><i class="fab fa-facebook-f"></i></a></li>
                                <li><a class="hover-target" href="https://www.linkedin.com/in/maureen-chepkemoi-97b9b4171/"><i class="fab fa-linkedin-in"></i></a></li>
                                <li><a class="hover-target" href="https://github.com/chepkemoi-maureen/maureen-portfolio"><i class="fab fa-github"></i></a></li>
                    
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- =============== 1.9 Contact Area End ====================-->
{% endblock %}

templates/portfolio/layouts/base.html
<!DOCTYPE html>
<html lang="zxx">
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" type="image/png" href="{% static 'assets/image/logo/favicon.ico' %}">
    <title>Lizu - Portfolio Responsive HTML Template</title>
    {% include 'portfolio/include/styles.html' %}
</head>

<body>
    <!-- ===============  preloader Area Start ====================-->
    <div id="preloader">
        <div class="loader">
            <img src="{% static 'assets/image/logo/loader.gif' %}" alt="preloader">
        </div>
    </div>
<!--    header-->
    {% include 'portfolio/components/header.html' %}
    {% block content %}{% endblock %}
    <!-- ===============  preloader Area End ====================-->
    <!-- =============== 1.9 Footer Area Start ====================-->
    <footer>
        <p><a target="_blank" href="#">{% now "Y" %}</a></p>
    </footer>
    {% include 'portfolio/include/scripts.html' %}
</body>
</html>